import React,{useState}from'react';import{Outlet,Link,useLocation,useNavigate}from'react-router-dom';import{useDispatch,useSelector}from'react-redux';import{logout}from'../../store/slices/authSlice';import{IconButton,Avatar,Menu,MenuItem,Divider}from'@mui/material';import{Dashboard,RequestQuote,Build,FolderOpen,Support,Menu as MenuIcon,Close,Logout,Settings}from'@mui/icons-material';
const NAV=[{icon:<Dashboard fontSize="small"/>,label:'Dashboard',to:'/portal'},{icon:<RequestQuote fontSize="small"/>,label:'Quotations',to:'/portal/quotations'},{icon:<Build fontSize="small"/>,label:'My Projects',to:'/portal/projects'},{icon:<FolderOpen fontSize="small"/>,label:'Documents',to:'/portal/documents'},{icon:<Support fontSize="small"/>,label:'Support',to:'/portal/tickets'}];
export default function PortalLayout(){const{user}=useSelector(s=>s.auth);const dispatch=useDispatch();const navigate=useNavigate();const location=useLocation();const[sideOpen,setSideOpen]=useState(true);const[anchor,setAnchor]=useState(null);
const handleLogout=()=>{dispatch(logout());navigate('/login');};
return(<div className="flex min-h-screen bg-gray-50">
<aside className={`${sideOpen?'w-60':'w-16'} bg-white border-r border-gray-100 flex flex-col transition-all duration-200 flex-shrink-0`}>
<div className="flex items-center gap-3 px-4 py-4 border-b border-gray-100"><div className="w-8 h-8 rounded-lg bg-gradient-to-br from-primary-500 to-secondary-500 flex items-center justify-center text-white text-xs font-bold flex-shrink-0">TS</div>{sideOpen&&<span className="font-bold text-dark-800 text-sm">Customer Portal</span>}</div>
<nav className="flex-1 p-2 space-y-1">{NAV.map(n=>{const active=location.pathname===n.to||location.pathname.startsWith(n.to+'/');return(<Link key={n.to} to={n.to} className={`flex items-center gap-3 px-3 py-2 rounded-lg transition-colors text-sm font-medium ${active?'bg-primary-50 text-primary-600':'text-gray-600 hover:bg-gray-50 hover:text-dark-800'}`}><span className="flex-shrink-0">{n.icon}</span>{sideOpen&&<span>{n.label}</span>}</Link>);})}</nav>
<div className="p-2 border-t border-gray-100"><Link to="/request-solution" className={`flex items-center gap-3 px-3 py-2 rounded-lg bg-primary-500 text-white text-sm font-medium hover:bg-primary-600 transition-colors`}><span className="flex-shrink-0">➕</span>{sideOpen&&<span>New Request</span>}</Link></div>
</aside>
<div className="flex-1 flex flex-col min-w-0">
<header className="bg-white border-b border-gray-100 px-6 py-3 flex items-center justify-between"><IconButton size="small" onClick={()=>setSideOpen(v=>!v)}>{sideOpen?<Close fontSize="small"/>:<MenuIcon fontSize="small"/>}</IconButton>
<div className="flex items-center gap-3"><span className="text-sm text-gray-500 hidden sm:block">{user?.Email}</span><Avatar onClick={e=>setAnchor(e.currentTarget)} sx={{width:32,height:32,bgcolor:'#0052cc',fontSize:13,cursor:'pointer'}}>{user?.FirstName?.[0]||'U'}</Avatar></div>
<Menu anchorEl={anchor} open={!!anchor} onClose={()=>setAnchor(null)}><MenuItem component={Link} to="/portal/profile" onClick={()=>setAnchor(null)}><Settings fontSize="small" sx={{mr:1}}/>Profile</MenuItem><Divider/><MenuItem onClick={handleLogout} sx={{color:'error.main'}}><Logout fontSize="small" sx={{mr:1}}/>Logout</MenuItem></Menu>
</header>
<main className="flex-1 overflow-auto p-6"><Outlet/></main></div></div>);}
