import React,{useEffect,useState}from'react';import{Link}from'react-router-dom';import{useSelector}from'react-redux';import{CircularProgress,Chip}from'@mui/material';import api from'../../services/api';
const SC={New:'error','In Progress':'warning','Quotation Sent':'info','Won':'success','Lost':'default'};
export default function PortalDashboard(){const{user}=useSelector(s=>s.auth);const[data,setData]=useState(null);const[loading,setLoading]=useState(true);
useEffect(()=>{Promise.all([api.get('/portal/inquiries?limit=5'),api.get('/portal/tickets?limit=5')]).then(([inq,tickets])=>setData({inquiries:inq.data.data||[],tickets:tickets.data.data||[]})).catch(()=>setData({inquiries:[],tickets:[]})).finally(()=>setLoading(false));},[]);
if(loading)return<div className="flex justify-center py-16"><CircularProgress/></div>;
return(<div className="space-y-6"><div className="bg-gradient-to-r from-primary-500 to-secondary-500 rounded-2xl p-6 text-white"><h1 className="text-2xl font-bold">Welcome back, {user?.FirstName||'Customer'} 👋</h1><p className="text-blue-100 mt-1">Here's an overview of your account with V-Trinity Solutions.</p></div>
<div className="grid sm:grid-cols-3 gap-4"><Link to="/portal/quotations" className="bg-white rounded-xl p-5 shadow-sm hover:shadow-md transition-shadow text-center"><div className="text-3xl font-black text-primary-600">{data.inquiries.length}</div><div className="text-gray-500 text-sm mt-1">Active Requests</div></Link><Link to="/portal/tickets" className="bg-white rounded-xl p-5 shadow-sm hover:shadow-md transition-shadow text-center"><div className="text-3xl font-black text-orange-500">{data.tickets.length}</div><div className="text-gray-500 text-sm mt-1">Support Tickets</div></Link><Link to="/request-solution" className="bg-primary-50 rounded-xl p-5 shadow-sm hover:shadow-md transition-shadow text-center flex flex-col items-center justify-center"><div className="text-3xl mb-1">➕</div><div className="text-primary-600 font-semibold text-sm">New Request</div></Link></div>
<div className="bg-white rounded-2xl shadow-sm"><div className="px-6 py-4 border-b border-gray-100 flex items-center justify-between"><h2 className="font-semibold text-dark-800">Recent Requests</h2><Link to="/portal/quotations" className="text-primary-500 text-sm">View all →</Link></div>
{data.inquiries.length?<div className="divide-y divide-gray-50">{data.inquiries.map(inq=><div key={inq.InquiryID} className="px-6 py-4 flex items-center justify-between"><div><div className="font-medium text-dark-800 text-sm">{inq.Subject||inq.InquiryType}</div><div className="text-xs text-gray-400 mt-0.5">{inq.CreatedAt?new Date(inq.CreatedAt).toLocaleDateString():''}</div></div><Chip label={inq.Status} color={SC[inq.Status]||'default'} size="small"/></div>)}</div>:<div className="px-6 py-8 text-center text-gray-400">No requests yet. <Link to="/request-solution" className="text-primary-500">Submit your first request →</Link></div>}</div></div>);}


