import React,{useEffect,useState}from'react';import{CircularProgress,Chip,TextField,Button,Dialog,DialogTitle,DialogContent,DialogActions,Alert,MenuItem}from'@mui/material';import{Add}from'@mui/icons-material';import api from'../../services/api';
const SC={Open:'error',Pending:'warning','In Progress':'info',Resolved:'success',Closed:'default'};
const PRIORITIES=['Low','Medium','High','Urgent'];
export default function PortalTickets(){const[rows,setRows]=useState([]);const[loading,setLoading]=useState(true);const[open,setOpen]=useState(false);const[form,setForm]=useState({Subject:'',Description:'',Priority:'Medium'});const[saving,setSaving]=useState(false);const[err,setErr]=useState('');
const load=()=>{setLoading(true);api.get('/portal/tickets').then(r=>setRows(r.data.data||[])).finally(()=>setLoading(false));};
useEffect(()=>{load();},[]);
const submit=async()=>{setSaving(true);setErr('');try{await api.post('/support/tickets',form);setOpen(false);setForm({Subject:'',Description:'',Priority:'Medium'});load();}catch(e){setErr(e.response?.data?.message||'Submit failed');}finally{setSaving(false);}};
return(<div className="space-y-4"><div className="flex items-center justify-between"><h1 className="text-xl font-bold font-heading text-dark-800">Support Tickets</h1><Button variant="contained" startIcon={<Add/>} onClick={()=>{setErr('');setOpen(true);}} sx={{background:'linear-gradient(135deg,#0052cc,#003d99)'}}>New Ticket</Button></div>
{loading?<div className="flex justify-center py-12"><CircularProgress/></div>:<div className="bg-white rounded-2xl shadow-sm overflow-hidden">{rows.length?<div className="divide-y divide-gray-50">{rows.map(r=><div key={r.TicketID} className="px-6 py-4 flex flex-col sm:flex-row sm:items-center justify-between gap-2"><div><div className="font-medium text-dark-800 text-sm">{r.Subject}</div><div className="text-xs text-gray-400 mt-0.5">#{r.TicketID} • {r.Priority} • {r.CreatedAt?new Date(r.CreatedAt).toLocaleDateString():''}</div></div><Chip label={r.Status||'Open'} color={SC[r.Status||'Open']||'default'} size="small"/></div>)}</div>:<div className="px-6 py-12 text-center"><div className="text-4xl mb-3">🎫</div><p className="text-gray-500">No support tickets yet.</p></div>}</div>}
<Dialog open={open} onClose={()=>setOpen(false)} maxWidth="sm" fullWidth><DialogTitle>New Support Ticket</DialogTitle><DialogContent><div className="space-y-4 pt-2">{err&&<Alert severity="error">{err}</Alert>}<TextField fullWidth label="Subject *" required value={form.Subject} onChange={e=>setForm(f=>({...f,Subject:e.target.value}))}/><TextField select fullWidth label="Priority" value={form.Priority} onChange={e=>setForm(f=>({...f,Priority:e.target.value}))}>{PRIORITIES.map(p=><MenuItem key={p} value={p}>{p}</MenuItem>)}</TextField><TextField fullWidth multiline rows={5} label="Description *" required value={form.Description} onChange={e=>setForm(f=>({...f,Description:e.target.value}))}/></div></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="contained" onClick={submit} disabled={saving}>{saving?'Submitting...':'Submit Ticket'}</Button></DialogActions></Dialog></div>);}
