import React,{useEffect,useState}from'react';import{Button,TextField,Dialog,DialogTitle,DialogContent,DialogActions,Table,TableHead,TableRow,TableCell,TableBody,TablePagination,Chip,IconButton,CircularProgress,Alert,MenuItem}from'@mui/material';import{Add,Edit,Delete}from'@mui/icons-material';import api from'../../services/api';
const STATUS=['draft','published','archived'];
export default function AdminBlog(){const[rows,setRows]=useState([]);const[total,setTotal]=useState(0);const[page,setPage]=useState(0);const[loading,setLoading]=useState(true);const[open,setOpen]=useState(false);const[editing,setEditing]=useState(null);const[form,setForm]=useState({Title:'',Excerpt:'',Status:'draft'});const[saving,setSaving]=useState(false);const[err,setErr]=useState('');
const load=async()=>{setLoading(true);try{const r=await api.get(`/blog?page=${page+1}&limit=10`);setRows(r.data.data);setTotal(r.data.pagination?.total||0);}finally{setLoading(false);}};
useEffect(()=>{load();},[page]);
const openCreate=()=>{setEditing(null);setForm({Title:'',Excerpt:'',Status:'draft'});setErr('');setOpen(true);};
const openEdit=(r)=>{setEditing(r);setForm({Title:r.Title,Excerpt:r.Excerpt||'',Status:r.Status||'draft'});setErr('');setOpen(true);};
const save=async()=>{setSaving(true);setErr('');try{if(editing){await api.put(`/blog/${editing.PostID}`,form);}else{await api.post('/blog',form);}setOpen(false);load();}catch(e){setErr(e.response?.data?.message||'Save failed');}finally{setSaving(false);}};
const del=async(id)=>{if(!window.confirm('Delete this post?'))return;await api.delete(`/blog/${id}`);load();};
const sc={draft:'default',published:'success',archived:'warning'};
return(<div className="p-6"><div className="flex items-center justify-between mb-6"><h1 className="text-2xl font-bold font-heading text-dark-800">Blog Posts</h1><Button variant="contained" startIcon={<Add/>} onClick={openCreate} sx={{background:'linear-gradient(135deg,#0052cc,#003d99)'}}>New Post</Button></div>
{loading?<CircularProgress/>:<><Table size="small"><TableHead><TableRow><TableCell>Title</TableCell><TableCell>Status</TableCell><TableCell>Author</TableCell><TableCell>Date</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{rows.map(r=><TableRow key={r.PostID} hover><TableCell className="font-medium">{r.Title}</TableCell><TableCell><Chip label={r.Status} color={sc[r.Status]||'default'} size="small"/></TableCell><TableCell>{r.AuthorName||'-'}</TableCell><TableCell>{r.PublishedAt?new Date(r.PublishedAt).toLocaleDateString():'-'}</TableCell><TableCell align="right"><IconButton size="small" onClick={()=>openEdit(r)}><Edit fontSize="small"/></IconButton><IconButton size="small" color="error" onClick={()=>del(r.PostID)}><Delete fontSize="small"/></IconButton></TableCell></TableRow>)}</TableBody></Table>
<TablePagination component="div" count={total} page={page} rowsPerPage={10} rowsPerPageOptions={[10]} onPageChange={(_,p)=>setPage(p)}/></>}
<Dialog open={open} onClose={()=>setOpen(false)} maxWidth="sm" fullWidth><DialogTitle>{editing?'Edit Post':'New Blog Post'}</DialogTitle><DialogContent><div className="space-y-4 pt-2">{err&&<Alert severity="error">{err}</Alert>}<TextField fullWidth label="Title *" required value={form.Title} onChange={e=>setForm(f=>({...f,Title:e.target.value}))}/><TextField fullWidth multiline rows={3} label="Excerpt" value={form.Excerpt} onChange={e=>setForm(f=>({...f,Excerpt:e.target.value}))}/><TextField select fullWidth label="Status" value={form.Status} onChange={e=>setForm(f=>({...f,Status:e.target.value}))}>{STATUS.map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField></div></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="contained" onClick={save} disabled={saving}>{saving?'Saving...':'Save'}</Button></DialogActions></Dialog></div>);}
