import React,{useEffect,useState}from'react';import{Button,Table,TableHead,TableRow,TableCell,TableBody,Chip,IconButton,CircularProgress,Dialog,DialogTitle,DialogContent,DialogActions,TextField,Alert,Switch,TablePagination}from'@mui/material';import{Add,Edit,Delete,Visibility}from'@mui/icons-material';import api from'../../services/api';
export default function AdminCaseStudies(){const[rows,setRows]=useState([]);const[total,setTotal]=useState(0);const[page,setPage]=useState(0);const[loading,setLoading]=useState(true);const[open,setOpen]=useState(false);const[editing,setEditing]=useState(null);const[form,setForm]=useState({Title:'',Client:'',Industry:'',Challenge:'',Solution:'',Results:'',IsActive:true});const[saving,setSaving]=useState(false);const[err,setErr]=useState('');
const load=async()=>{setLoading(true);try{const r=await api.get(`/case-studies?page=${page+1}&limit=10`);setRows(r.data.data||[]);setTotal(r.data.pagination?.total||0);}catch{setRows([]);}finally{setLoading(false);}};
useEffect(()=>{load();},[page]);
const openCreate=()=>{setEditing(null);setForm({Title:'',Client:'',Industry:'',Challenge:'',Solution:'',Results:'',IsActive:true});setErr('');setOpen(true);};
const openEdit=(r)=>{setEditing(r);setForm({Title:r.Title,Client:r.Client||'',Industry:r.Industry||'',Challenge:r.Challenge||'',Solution:r.Solution||'',Results:r.Results||'',IsActive:r.IsActive!==false});setErr('');setOpen(true);};
const save=async()=>{setSaving(true);setErr('');try{if(editing){await api.put(`/case-studies/${editing.CaseStudyID}`,form);}else{await api.post('/case-studies',form);}setOpen(false);load();}catch(e){setErr(e.response?.data?.message||'Save failed');}finally{setSaving(false);}};
const del=async(id)=>{if(!window.confirm('Delete this case study?'))return;await api.delete(`/case-studies/${id}`);load();};
return(<div className="p-6"><div className="flex items-center justify-between mb-6"><h1 className="text-2xl font-bold font-heading text-dark-800">Case Studies</h1><Button variant="contained" startIcon={<Add/>} onClick={openCreate} sx={{background:'linear-gradient(135deg,#0052cc,#003d99)'}}>Add Case Study</Button></div>
{loading?<CircularProgress/>:<><Table size="small"><TableHead><TableRow><TableCell>Title</TableCell><TableCell>Client</TableCell><TableCell>Industry</TableCell><TableCell>Status</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{rows.map(r=><TableRow key={r.CaseStudyID} hover><TableCell className="font-medium" sx={{maxWidth:250}}>{r.Title}</TableCell><TableCell>{r.Client||'—'}</TableCell><TableCell>{r.Industry||'—'}</TableCell><TableCell><Chip label={r.IsActive?'Published':'Draft'} color={r.IsActive?'success':'default'} size="small"/></TableCell><TableCell align="right"><IconButton size="small" onClick={()=>openEdit(r)}><Edit fontSize="small"/></IconButton><IconButton size="small" color="error" onClick={()=>del(r.CaseStudyID)}><Delete fontSize="small"/></IconButton></TableCell></TableRow>)}</TableBody></Table>
<TablePagination component="div" count={total} page={page} rowsPerPage={10} rowsPerPageOptions={[10]} onPageChange={(_,p)=>setPage(p)}/></>}
<Dialog open={open} onClose={()=>setOpen(false)} maxWidth="md" fullWidth><DialogTitle>{editing?'Edit Case Study':'Add Case Study'}</DialogTitle><DialogContent><div className="space-y-4 pt-2">{err&&<Alert severity="error">{err}</Alert>}<TextField fullWidth label="Title *" required value={form.Title} onChange={e=>setForm(f=>({...f,Title:e.target.value}))}/><div className="grid grid-cols-2 gap-3"><TextField fullWidth label="Client Name" value={form.Client} onChange={e=>setForm(f=>({...f,Client:e.target.value}))}/><TextField fullWidth label="Industry" value={form.Industry} onChange={e=>setForm(f=>({...f,Industry:e.target.value}))}/></div><TextField fullWidth multiline rows={3} label="Challenge" value={form.Challenge} onChange={e=>setForm(f=>({...f,Challenge:e.target.value}))}/><TextField fullWidth multiline rows={3} label="Solution" value={form.Solution} onChange={e=>setForm(f=>({...f,Solution:e.target.value}))}/><TextField fullWidth multiline rows={3} label="Results" value={form.Results} onChange={e=>setForm(f=>({...f,Results:e.target.value}))}/><div className="flex items-center gap-2"><Switch checked={form.IsActive} onChange={e=>setForm(f=>({...f,IsActive:e.target.checked}))}/><span className="text-sm text-gray-600">Published (visible on website)</span></div></div></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="contained" onClick={save} disabled={saving}>{saving?'Saving...':'Save'}</Button></DialogActions></Dialog></div>);}
