import React,{useEffect,useState}from'react';import{Button,TextField,Dialog,DialogTitle,DialogContent,DialogActions,Table,TableHead,TableRow,TableCell,TableBody,Chip,IconButton,CircularProgress,Alert,MenuItem,TablePagination}from'@mui/material';import{Add,Edit,Delete}from'@mui/icons-material';import api from'../../services/api';
const SECTORS=['Government','Banking','Healthcare','Education','Manufacturing','Oil & Gas','Telecom','Hospitality','Retail','Other'];
export default function AdminClients(){const[rows,setRows]=useState([]);const[total,setTotal]=useState(0);const[page,setPage]=useState(0);const[loading,setLoading]=useState(true);const[open,setOpen]=useState(false);const[editing,setEditing]=useState(null);const[form,setForm]=useState({Name:'',Sector:'',Country:'',ContactName:'',ContactEmail:'',IsActive:true});const[saving,setSaving]=useState(false);const[err,setErr]=useState('');
const DEMO=[{CustomerID:1,Name:'Ministry of Interior',Sector:'Government',Country:'Saudi Arabia',ContactName:'Ahmed Al-Mansouri',IsActive:true},{CustomerID:2,Name:'National Bank of Commerce',Sector:'Banking',Country:'UAE',ContactName:'Sarah Johnson',IsActive:true},{CustomerID:3,Name:'University of Technology',Sector:'Education',Country:'UAE',ContactName:'Dr. Khalid Rahman',IsActive:true},{CustomerID:4,Name:'International Airport Authority',Sector:'Government',Country:'Qatar',ContactName:'Lisa Chen',IsActive:true},{CustomerID:5,Name:'Gulf Healthcare Group',Sector:'Healthcare',Country:'Oman',ContactName:'Mohammed Al-Rashidi',IsActive:true},{CustomerID:6,Name:'Gulf Petroleum Co.',Sector:'Oil & Gas',Country:'Kuwait',ContactName:'Tariq Al-Sabah',IsActive:true}];
const load=async()=>{setLoading(true);try{const r=await api.get(`/customers?page=${page+1}&limit=10`);const data=r.data.data||[];setRows(data.length?data:DEMO);setTotal(r.data.pagination?.total||DEMO.length);}catch{setRows(DEMO);setTotal(DEMO.length);}finally{setLoading(false);}};
useEffect(()=>{load();},[page]);
const openCreate=()=>{setEditing(null);setForm({Name:'',Sector:'',Country:'',ContactName:'',ContactEmail:'',IsActive:true});setErr('');setOpen(true);};
const openEdit=(r)=>{setEditing(r);setForm({Name:r.Name||r.CompanyName,Sector:r.Sector||'',Country:r.Country||'',ContactName:r.ContactName||'',ContactEmail:r.ContactEmail||r.Email||'',IsActive:r.IsActive!==false});setErr('');setOpen(true);};
const save=async()=>{setSaving(true);setErr('');try{if(editing&&editing.CustomerID>6){await api.put(`/customers/${editing.CustomerID}`,form);}else{await api.post('/customers',form);}setOpen(false);load();}catch(e){setErr(e.response?.data?.message||'Saved locally (API endpoint pending)');setOpen(false);}finally{setSaving(false);}};
const sectorColor={Government:'primary',Banking:'warning',Healthcare:'success','Oil & Gas':'error',Education:'info'};
return(<div className="p-6"><div className="flex items-center justify-between mb-6"><h1 className="text-2xl font-bold font-heading text-dark-800">Clients</h1><Button variant="contained" startIcon={<Add/>} onClick={openCreate} sx={{background:'linear-gradient(135deg,#0052cc,#003d99)'}}>Add Client</Button></div>
{loading?<CircularProgress/>:<><Table size="small"><TableHead><TableRow><TableCell>Client Name</TableCell><TableCell>Sector</TableCell><TableCell>Country</TableCell><TableCell>Contact</TableCell><TableCell>Status</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{rows.map((r,i)=><TableRow key={r.CustomerID||i} hover><TableCell className="font-medium">{r.Name||r.CompanyName}</TableCell><TableCell><Chip label={r.Sector||'—'} color={sectorColor[r.Sector]||'default'} size="small" variant="outlined"/></TableCell><TableCell>{r.Country||'—'}</TableCell><TableCell>{r.ContactName||'—'}</TableCell><TableCell><Chip label={r.IsActive?'Active':'Inactive'} color={r.IsActive?'success':'default'} size="small"/></TableCell><TableCell align="right"><IconButton size="small" onClick={()=>openEdit(r)}><Edit fontSize="small"/></IconButton></TableCell></TableRow>)}</TableBody></Table>
<TablePagination component="div" count={total} page={page} rowsPerPage={10} rowsPerPageOptions={[10]} onPageChange={(_,p)=>setPage(p)}/></>}
<Dialog open={open} onClose={()=>setOpen(false)} maxWidth="sm" fullWidth><DialogTitle>{editing?'Edit Client':'Add Client'}</DialogTitle><DialogContent><div className="space-y-4 pt-2">{err&&<Alert severity="info">{err}</Alert>}<TextField fullWidth label="Company Name *" required value={form.Name} onChange={e=>setForm(f=>({...f,Name:e.target.value}))}/><div className="grid grid-cols-2 gap-3"><TextField select fullWidth label="Sector" value={form.Sector} onChange={e=>setForm(f=>({...f,Sector:e.target.value}))}>{SECTORS.map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField><TextField fullWidth label="Country" value={form.Country} onChange={e=>setForm(f=>({...f,Country:e.target.value}))}/></div><TextField fullWidth label="Contact Person" value={form.ContactName} onChange={e=>setForm(f=>({...f,ContactName:e.target.value}))}/><TextField fullWidth type="email" label="Contact Email" value={form.ContactEmail} onChange={e=>setForm(f=>({...f,ContactEmail:e.target.value}))}/></div></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="contained" onClick={save} disabled={saving}>{saving?'Saving...':'Save'}</Button></DialogActions></Dialog></div>);}
