import React,{useEffect,useState}from'react';import{Table,TableHead,TableRow,TableCell,TableBody,TablePagination,Chip,IconButton,Dialog,DialogTitle,DialogContent,DialogActions,Button,CircularProgress}from'@mui/material';import{Visibility}from'@mui/icons-material';import api from'../../services/api';
export default function AdminContactForms(){const[rows,setRows]=useState([]);const[total,setTotal]=useState(0);const[page,setPage]=useState(0);const[loading,setLoading]=useState(true);const[selected,setSelected]=useState(null);
const load=async()=>{setLoading(true);try{const r=await api.get(`/contact?page=${page+1}&limit=10`);setRows(r.data.data||[]);setTotal(r.data.pagination?.total||0);}finally{setLoading(false);}};
useEffect(()=>{load();},[page]);
const sc={new:'error',read:'warning',replied:'success'};
return(<div className="p-6"><h1 className="text-2xl font-bold font-heading text-dark-800 mb-6">Contact Form Submissions</h1>
{loading?<CircularProgress/>:<><Table size="small"><TableHead><TableRow><TableCell>Name</TableCell><TableCell>Email</TableCell><TableCell>Subject</TableCell><TableCell>Status</TableCell><TableCell>Date</TableCell><TableCell align="right">View</TableCell></TableRow></TableHead><TableBody>{rows.map(r=><TableRow key={r.ContactID} hover><TableCell>{r.FullName}</TableCell><TableCell>{r.Email}</TableCell><TableCell>{r.Subject||'-'}</TableCell><TableCell><Chip label={r.Status||'new'} color={sc[r.Status||'new']||'default'} size="small"/></TableCell><TableCell>{r.CreatedAt?new Date(r.CreatedAt).toLocaleDateString():'-'}</TableCell><TableCell align="right"><IconButton size="small" onClick={()=>setSelected(r)}><Visibility fontSize="small"/></IconButton></TableCell></TableRow>)}</TableBody></Table>
<TablePagination component="div" count={total} page={page} rowsPerPage={10} rowsPerPageOptions={[10]} onPageChange={(_,p)=>setPage(p)}/></>}
<Dialog open={!!selected} onClose={()=>setSelected(null)} maxWidth="sm" fullWidth><DialogTitle>Message from {selected?.FullName}</DialogTitle><DialogContent><div className="space-y-2 pt-1"><div className="text-sm text-gray-400">Email: {selected?.Email}</div>{selected?.Phone&&<div className="text-sm text-gray-400">Phone: {selected.Phone}</div>}{selected?.Subject&&<div className="font-medium mt-3">{selected.Subject}</div>}<div className="bg-gray-50 rounded-lg p-4 text-gray-700 whitespace-pre-wrap text-sm mt-2">{selected?.Message}</div></div></DialogContent><DialogActions><Button onClick={()=>setSelected(null)}>Close</Button><Button variant="contained" component="a" href={`mailto:${selected?.Email}`}>Reply via Email</Button></DialogActions></Dialog></div>);}
