import React,{useEffect,useState}from'react';import{Button,TextField,Dialog,DialogTitle,DialogContent,DialogActions,Table,TableHead,TableRow,TableCell,TableBody,Chip,IconButton,CircularProgress,Alert,Switch}from'@mui/material';import{Add,Edit,Delete}from'@mui/icons-material';import api from'../../services/api';
export default function AdminIndustries(){const[rows,setRows]=useState([]);const[loading,setLoading]=useState(true);const[open,setOpen]=useState(false);const[editing,setEditing]=useState(null);const[form,setForm]=useState({Name:'',Slug:'',Description:'',Icon:'',IsActive:true});const[saving,setSaving]=useState(false);const[err,setErr]=useState('');
const load=()=>{setLoading(true);api.get('/industries').then(r=>setRows(r.data.data||[])).catch(()=>setRows([])).finally(()=>setLoading(false));};
useEffect(()=>{load();},[]);
const openCreate=()=>{setEditing(null);setForm({Name:'',Slug:'',Description:'',Icon:'',IsActive:true});setErr('');setOpen(true);};
const openEdit=(r)=>{setEditing(r);setForm({Name:r.Name,Slug:r.Slug||'',Description:r.Description||'',Icon:r.Icon||'',IsActive:r.IsActive!==false});setErr('');setOpen(true);};
const save=async()=>{setSaving(true);setErr('');try{if(editing){await api.put(`/industries/${editing.IndustryID}`,form);}else{await api.post('/industries',form);}setOpen(false);load();}catch(e){setErr(e.response?.data?.message||'Save failed');}finally{setSaving(false);}};
const del=async(id)=>{if(!window.confirm('Delete this industry?'))return;await api.delete(`/industries/${id}`);load();};
return(<div className="p-6"><div className="flex items-center justify-between mb-6"><h1 className="text-2xl font-bold font-heading text-dark-800">Industries</h1><Button variant="contained" startIcon={<Add/>} onClick={openCreate} sx={{background:'linear-gradient(135deg,#0052cc,#003d99)'}}>Add Industry</Button></div>
{loading?<CircularProgress/>:<Table size="small"><TableHead><TableRow><TableCell>Name</TableCell><TableCell>Description</TableCell><TableCell>Active</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{rows.map(r=><TableRow key={r.IndustryID} hover><TableCell className="font-medium">{r.Icon&&<span className="mr-2">{r.Icon}</span>}{r.Name}</TableCell><TableCell sx={{maxWidth:300,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{r.Description||'—'}</TableCell><TableCell><Chip label={r.IsActive?'Active':'Hidden'} color={r.IsActive?'success':'default'} size="small"/></TableCell><TableCell align="right"><IconButton size="small" onClick={()=>openEdit(r)}><Edit fontSize="small"/></IconButton><IconButton size="small" color="error" onClick={()=>del(r.IndustryID)}><Delete fontSize="small"/></IconButton></TableCell></TableRow>)}</TableBody></Table>}
<Dialog open={open} onClose={()=>setOpen(false)} maxWidth="sm" fullWidth><DialogTitle>{editing?'Edit Industry':'Add Industry'}</DialogTitle><DialogContent><div className="space-y-4 pt-2">{err&&<Alert severity="error">{err}</Alert>}<TextField fullWidth label="Industry Name *" required value={form.Name} onChange={e=>setForm(f=>({...f,Name:e.target.value}))}/><TextField fullWidth label="Icon (emoji or CSS class)" value={form.Icon} onChange={e=>setForm(f=>({...f,Icon:e.target.value}))} helperText="e.g. 🏛️ or fas fa-landmark"/><TextField fullWidth multiline rows={3} label="Description" value={form.Description} onChange={e=>setForm(f=>({...f,Description:e.target.value}))}/><div className="flex items-center gap-2"><Switch checked={form.IsActive} onChange={e=>setForm(f=>({...f,IsActive:e.target.checked}))}/><span className="text-sm text-gray-600">Active (visible on website)</span></div></div></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="contained" onClick={save} disabled={saving}>{saving?'Saving...':'Save'}</Button></DialogActions></Dialog></div>);}
