import React,{useEffect,useState}from'react';import{Button,TextField,Dialog,DialogTitle,DialogContent,DialogActions,Table,TableHead,TableRow,TableCell,TableBody,TablePagination,Chip,IconButton,CircularProgress,Alert,MenuItem}from'@mui/material';import{Add,Edit,Delete}from'@mui/icons-material';import api from'../../services/api';
const STATUS=['Planning','In Progress','Completed'];
export default function AdminProjects(){const[rows,setRows]=useState([]);const[total,setTotal]=useState(0);const[page,setPage]=useState(0);const[loading,setLoading]=useState(true);const[open,setOpen]=useState(false);const[editing,setEditing]=useState(null);const[form,setForm]=useState({Title:'',ClientName:'',Status:'Planning',IsFeatured:false});const[saving,setSaving]=useState(false);const[err,setErr]=useState('');
const load=async()=>{setLoading(true);try{const r=await api.get(`/projects?page=${page+1}&limit=10`);setRows(r.data.data);setTotal(r.data.pagination?.total||r.data.data.length);}finally{setLoading(false);}};
useEffect(()=>{load();},[page]);
const openCreate=()=>{setEditing(null);setForm({Title:'',ClientName:'',Status:'Planning',IsFeatured:false});setErr('');setOpen(true);};
const openEdit=(r)=>{setEditing(r);setForm({Title:r.Title,ClientName:r.ClientName||'',Status:r.Status||'Planning',IsFeatured:!!r.IsFeatured});setErr('');setOpen(true);};
const save=async()=>{setSaving(true);setErr('');try{if(editing){await api.put(`/projects/${editing.ProjectID}`,form);}else{await api.post('/projects',form);}setOpen(false);load();}catch(e){setErr(e.response?.data?.message||'Save failed');}finally{setSaving(false);}};
const del=async(id)=>{if(!window.confirm('Delete this project?'))return;await api.delete(`/projects/${id}`);load();};
const statusColors={Planning:'info','In Progress':'warning',Completed:'success'};
return(<div className="p-6"><div className="flex items-center justify-between mb-6"><h1 className="text-2xl font-bold font-heading text-dark-800">Projects</h1><Button variant="contained" startIcon={<Add/>} onClick={openCreate} sx={{background:'linear-gradient(135deg,#0052cc,#003d99)'}}>Add Project</Button></div>
{loading?<CircularProgress/>:<><Table size="small"><TableHead><TableRow><TableCell>Title</TableCell><TableCell>Client</TableCell><TableCell>Status</TableCell><TableCell>Featured</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{rows.map(r=><TableRow key={r.ProjectID} hover><TableCell className="font-medium">{r.Title}</TableCell><TableCell>{r.ClientName||'-'}</TableCell><TableCell><Chip label={r.Status} color={statusColors[r.Status]||'default'} size="small"/></TableCell><TableCell>{r.IsFeatured?'⭐':'-'}</TableCell><TableCell align="right"><IconButton size="small" onClick={()=>openEdit(r)}><Edit fontSize="small"/></IconButton><IconButton size="small" color="error" onClick={()=>del(r.ProjectID)}><Delete fontSize="small"/></IconButton></TableCell></TableRow>)}</TableBody></Table>
<TablePagination component="div" count={total} page={page} rowsPerPage={10} rowsPerPageOptions={[10]} onPageChange={(_,p)=>setPage(p)}/></>}
<Dialog open={open} onClose={()=>setOpen(false)} maxWidth="sm" fullWidth><DialogTitle>{editing?'Edit Project':'Add Project'}</DialogTitle><DialogContent><div className="space-y-4 pt-2">{err&&<Alert severity="error">{err}</Alert>}<TextField fullWidth label="Project Title *" required value={form.Title} onChange={e=>setForm(f=>({...f,Title:e.target.value}))}/><TextField fullWidth label="Client Name" value={form.ClientName} onChange={e=>setForm(f=>({...f,ClientName:e.target.value}))}/><TextField select fullWidth label="Status" value={form.Status} onChange={e=>setForm(f=>({...f,Status:e.target.value}))}>{STATUS.map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField></div></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="contained" onClick={save} disabled={saving}>{saving?'Saving...':'Save'}</Button></DialogActions></Dialog></div>);}
