import React,{useEffect,useState}from'react';import{Table,TableHead,TableRow,TableCell,TableBody,IconButton,Dialog,DialogTitle,DialogContent,DialogActions,Button,TextField,Alert,CircularProgress}from'@mui/material';import{Edit}from'@mui/icons-material';import api from'../../services/api';
export default function AdminSEO(){const[rows,setRows]=useState([]);const[loading,setLoading]=useState(true);const[open,setOpen]=useState(false);const[editing,setEditing]=useState(null);const[form,setForm]=useState({MetaTitle:'',MetaDescription:'',MetaKeywords:''});const[saving,setSaving]=useState(false);const[err,setErr]=useState('');
const load=()=>{setLoading(true);api.get('/seo').then(r=>setRows(r.data.data||[])).finally(()=>setLoading(false));};
useEffect(()=>{load();},[]);
const openEdit=(r)=>{setEditing(r);setForm({MetaTitle:r.MetaTitle||'',MetaDescription:r.MetaDescription||'',MetaKeywords:r.MetaKeywords||''});setErr('');setOpen(true);};
const save=async()=>{setSaving(true);setErr('');try{await api.put(`/seo/${editing.PageID}`,form);setOpen(false);load();}catch(e){setErr(e.response?.data?.message||'Save failed');}finally{setSaving(false);}};
return(<div className="p-6"><h1 className="text-2xl font-bold font-heading text-dark-800 mb-6">SEO Manager</h1>
{loading?<CircularProgress/>:<Table size="small"><TableHead><TableRow><TableCell>Page</TableCell><TableCell>Meta Title</TableCell><TableCell>Description Preview</TableCell><TableCell align="right">Edit</TableCell></TableRow></TableHead><TableBody>{rows.map(r=><TableRow key={r.PageID} hover><TableCell className="font-medium capitalize">{r.PageSlug}</TableCell><TableCell>{r.MetaTitle||<span className="text-gray-400">—</span>}</TableCell><TableCell sx={{maxWidth:300,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{r.MetaDescription||<span className="text-gray-400">—</span>}</TableCell><TableCell align="right"><IconButton size="small" onClick={()=>openEdit(r)}><Edit fontSize="small"/></IconButton></TableCell></TableRow>)}</TableBody></Table>}
<Dialog open={open} onClose={()=>setOpen(false)} maxWidth="sm" fullWidth><DialogTitle>Edit SEO – {editing?.PageSlug}</DialogTitle><DialogContent><div className="space-y-4 pt-2">{err&&<Alert severity="error">{err}</Alert>}<TextField fullWidth label="Meta Title" value={form.MetaTitle} onChange={e=>setForm(f=>({...f,MetaTitle:e.target.value}))} helperText={`${form.MetaTitle.length}/60 chars`}/><TextField fullWidth multiline rows={3} label="Meta Description" value={form.MetaDescription} onChange={e=>setForm(f=>({...f,MetaDescription:e.target.value}))} helperText={`${form.MetaDescription.length}/160 chars`}/><TextField fullWidth label="Keywords (comma-separated)" value={form.MetaKeywords} onChange={e=>setForm(f=>({...f,MetaKeywords:e.target.value}))}/></div></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="contained" onClick={save} disabled={saving}>{saving?'Saving...':'Save'}</Button></DialogActions></Dialog></div>);}
