import React,{useEffect,useState}from'react';import{Button,TextField,Dialog,DialogTitle,DialogContent,DialogActions,Table,TableHead,TableRow,TableCell,TableBody,TablePagination,Chip,IconButton,CircularProgress,Alert,Switch}from'@mui/material';import{Add,Edit,Delete}from'@mui/icons-material';import api from'../../services/api';
export default function AdminServices(){const[rows,setRows]=useState([]);const[total,setTotal]=useState(0);const[page,setPage]=useState(0);const[loading,setLoading]=useState(true);const[open,setOpen]=useState(false);const[editing,setEditing]=useState(null);const[form,setForm]=useState({Name:'',ShortDescription:'',CategoryID:'',IsActive:true});const[saving,setSaving]=useState(false);const[err,setErr]=useState('');
const load=async()=>{setLoading(true);try{const r=await api.get(`/services?page=${page+1}&limit=10`);setRows(r.data.data);setTotal(r.data.pagination?.total||r.data.data.length);}finally{setLoading(false);}};
useEffect(()=>{load();},[page]);
const openCreate=()=>{setEditing(null);setForm({Name:'',ShortDescription:'',CategoryID:'',IsActive:true});setErr('');setOpen(true);};
const openEdit=(r)=>{setEditing(r);setForm({Name:r.Name,ShortDescription:r.ShortDescription||'',CategoryID:r.CategoryID||'',IsActive:r.IsActive!==false});setErr('');setOpen(true);};
const save=async()=>{setSaving(true);setErr('');try{if(editing){await api.put(`/services/${editing.ServiceID}`,form);}else{await api.post('/services',form);}setOpen(false);load();}catch(e){setErr(e.response?.data?.message||'Save failed');}finally{setSaving(false);}};
const del=async(id)=>{if(!window.confirm('Delete this service?'))return;await api.delete(`/services/${id}`);load();};
return(<div className="p-6"><div className="flex items-center justify-between mb-6"><h1 className="text-2xl font-bold font-heading text-dark-800">Services</h1><Button variant="contained" startIcon={<Add/>} onClick={openCreate} sx={{background:'linear-gradient(135deg,#0052cc,#003d99)'}}>Add Service</Button></div>
{loading?<CircularProgress/>:<><Table size="small"><TableHead><TableRow><TableCell>Name</TableCell><TableCell>Category</TableCell><TableCell>Active</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{rows.map(r=><TableRow key={r.ServiceID} hover><TableCell>{r.Name}</TableCell><TableCell>{r.CategoryName||'-'}</TableCell><TableCell><Chip label={r.IsActive?'Active':'Inactive'} color={r.IsActive?'success':'default'} size="small"/></TableCell><TableCell align="right"><IconButton size="small" onClick={()=>openEdit(r)}><Edit fontSize="small"/></IconButton><IconButton size="small" color="error" onClick={()=>del(r.ServiceID)}><Delete fontSize="small"/></IconButton></TableCell></TableRow>)}</TableBody></Table>
<TablePagination component="div" count={total} page={page} rowsPerPage={10} rowsPerPageOptions={[10]} onPageChange={(_,p)=>setPage(p)}/></>}
<Dialog open={open} onClose={()=>setOpen(false)} maxWidth="sm" fullWidth><DialogTitle>{editing?'Edit Service':'Add Service'}</DialogTitle><DialogContent><div className="space-y-4 pt-2">{err&&<Alert severity="error">{err}</Alert>}<TextField fullWidth label="Service Name *" required value={form.Name} onChange={e=>setForm(f=>({...f,Name:e.target.value}))}/><TextField fullWidth multiline rows={3} label="Short Description" value={form.ShortDescription} onChange={e=>setForm(f=>({...f,ShortDescription:e.target.value}))}/><div className="flex items-center gap-2"><Switch checked={form.IsActive} onChange={e=>setForm(f=>({...f,IsActive:e.target.checked}))}/><span className="text-sm text-gray-600">Active (visible on website)</span></div></div></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="contained" onClick={save} disabled={saving}>{saving?'Saving...':'Save'}</Button></DialogActions></Dialog></div>);}
