import React,{useEffect,useState}from'react';import{TextField,Button,Alert,CircularProgress,Divider,Switch}from'@mui/material';import{Save}from'@mui/icons-material';import api from'../../services/api';
export default function AdminSettings(){const[settings,setSettings]=useState({});const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[success,setSuccess]=useState(false);const[err,setErr]=useState('');
useEffect(()=>{api.get('/settings').then(r=>{const map={};(r.data.data||[]).forEach(s=>{map[s.SettingKey]=s.SettingValue;});setSettings(map);}).finally(()=>setLoading(false));},[]);
const f=(key,label,type='text',multiline=false)=>(<TextField key={key} fullWidth label={label} type={type} multiline={multiline} rows={multiline?3:1} value={settings[key]||''} onChange={e=>setSettings(s=>({...s,[key]:e.target.value}))} size="small" sx={{mb:2}}/>);
const save=async()=>{setSaving(true);setErr('');setSuccess(false);try{const entries=Object.entries(settings).map(([SettingKey,SettingValue])=>({SettingKey,SettingValue}));await api.put('/settings',{settings:entries});setSuccess(true);setTimeout(()=>setSuccess(false),3000);}catch(e){setErr(e.response?.data?.message||'Save failed');}finally{setSaving(false);}};
if(loading)return<div className="p-6"><CircularProgress/></div>;
return(<div className="p-6 max-w-2xl"><div className="flex items-center justify-between mb-6"><h1 className="text-2xl font-bold font-heading text-dark-800">Website Settings</h1><Button variant="contained" startIcon={<Save/>} onClick={save} disabled={saving} sx={{background:'linear-gradient(135deg,#0052cc,#003d99)'}}>{saving?'Saving...':'Save Settings'}</Button></div>
{success&&<Alert severity="success" sx={{mb:3}}>Settings saved successfully!</Alert>}
{err&&<Alert severity="error" sx={{mb:3}}>{err}</Alert>}
<div className="bg-white rounded-2xl p-6 shadow-sm mb-4"><h2 className="font-semibold text-dark-800 mb-4">Company Information</h2>{f('site_name','Company Name')}{f('site_tagline','Tagline')}{f('company_email','Company Email','email')}{f('company_phone','Phone Number')}{f('company_address','Address',undefined,true)}</div>
<div className="bg-white rounded-2xl p-6 shadow-sm mb-4"><h2 className="font-semibold text-dark-800 mb-4">Social Media</h2>{f('social_linkedin','LinkedIn URL')}{f('social_twitter','Twitter/X URL')}{f('social_facebook','Facebook URL')}{f('social_instagram','Instagram URL')}</div>
<div className="bg-white rounded-2xl p-6 shadow-sm"><h2 className="font-semibold text-dark-800 mb-4">SEO Defaults</h2>{f('seo_default_title','Default Page Title')}{f('seo_default_description','Default Meta Description',undefined,true)}{f('google_analytics_id','Google Analytics ID')}</div></div>);}
