import React,{useEffect,useState}from'react';import{Button,TextField,Dialog,DialogTitle,DialogContent,DialogActions,Table,TableHead,TableRow,TableCell,TableBody,TablePagination,Chip,IconButton,CircularProgress,Alert,Switch}from'@mui/material';import{Add,Edit,Delete}from'@mui/icons-material';import api from'../../services/api';
export default function AdminSolutions(){const[rows,setRows]=useState([]);const[total,setTotal]=useState(0);const[page,setPage]=useState(0);const[loading,setLoading]=useState(true);const[open,setOpen]=useState(false);const[editing,setEditing]=useState(null);const[form,setForm]=useState({Title:'',Description:'',IsActive:true});const[saving,setSaving]=useState(false);const[err,setErr]=useState('');
const load=async()=>{setLoading(true);try{const r=await api.get(`/solutions?page=${page+1}&limit=10`);setRows(r.data.data||[]);setTotal(r.data.pagination?.total||0);}finally{setLoading(false);}};
useEffect(()=>{load();},[page]);
const openCreate=()=>{setEditing(null);setForm({Title:'',Description:'',IsActive:true});setErr('');setOpen(true);};
const openEdit=(r)=>{setEditing(r);setForm({Title:r.Title,Description:r.Description||'',IsActive:r.IsActive!==false});setErr('');setOpen(true);};
const save=async()=>{setSaving(true);setErr('');try{if(editing){await api.put(`/solutions/${editing.SolutionID}`,form);}else{await api.post('/solutions',form);}setOpen(false);load();}catch(e){setErr(e.response?.data?.message||'Save failed');}finally{setSaving(false);}};
const del=async(id)=>{if(!window.confirm('Delete?'))return;await api.delete(`/solutions/${id}`);load();};
return(<div className="p-6"><div className="flex items-center justify-between mb-6"><h1 className="text-2xl font-bold font-heading text-dark-800">Solutions</h1><Button variant="contained" startIcon={<Add/>} onClick={openCreate} sx={{background:'linear-gradient(135deg,#0052cc,#003d99)'}}>Add Solution</Button></div>
{loading?<CircularProgress/>:<><Table size="small"><TableHead><TableRow><TableCell>Title</TableCell><TableCell>Active</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{rows.map(r=><TableRow key={r.SolutionID} hover><TableCell className="font-medium">{r.Title}</TableCell><TableCell><Chip label={r.IsActive?'Active':'Hidden'} color={r.IsActive?'success':'default'} size="small"/></TableCell><TableCell align="right"><IconButton size="small" onClick={()=>openEdit(r)}><Edit fontSize="small"/></IconButton><IconButton size="small" color="error" onClick={()=>del(r.SolutionID)}><Delete fontSize="small"/></IconButton></TableCell></TableRow>)}</TableBody></Table>
<TablePagination component="div" count={total} page={page} rowsPerPage={10} rowsPerPageOptions={[10]} onPageChange={(_,p)=>setPage(p)}/></>}
<Dialog open={open} onClose={()=>setOpen(false)} maxWidth="sm" fullWidth><DialogTitle>{editing?'Edit Solution':'Add Solution'}</DialogTitle><DialogContent><div className="space-y-4 pt-2">{err&&<Alert severity="error">{err}</Alert>}<TextField fullWidth label="Title *" required value={form.Title} onChange={e=>setForm(f=>({...f,Title:e.target.value}))}/><TextField fullWidth multiline rows={4} label="Description" value={form.Description} onChange={e=>setForm(f=>({...f,Description:e.target.value}))}/><div className="flex items-center gap-2"><Switch checked={form.IsActive} onChange={e=>setForm(f=>({...f,IsActive:e.target.checked}))}/><span className="text-sm text-gray-600">Active</span></div></div></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="contained" onClick={save} disabled={saving}>{saving?'Saving...':'Save'}</Button></DialogActions></Dialog></div>);}
