import React,{useEffect,useState}from'react';import{Button,TextField,Dialog,DialogTitle,DialogContent,DialogActions,Table,TableHead,TableRow,TableCell,TableBody,Chip,IconButton,CircularProgress,Alert,Switch,Rating}from'@mui/material';import{Add,Edit,Delete}from'@mui/icons-material';import api from'../../services/api';
export default function AdminTestimonials(){const[rows,setRows]=useState([]);const[loading,setLoading]=useState(true);const[open,setOpen]=useState(false);const[editing,setEditing]=useState(null);const[form,setForm]=useState({ClientName:'',ClientTitle:'',ClientCompany:'',Review:'',Rating:5,IsActive:true});const[saving,setSaving]=useState(false);const[err,setErr]=useState('');
const load=()=>{setLoading(true);api.get('/testimonials').then(r=>setRows(r.data.data||[])).finally(()=>setLoading(false));};
useEffect(()=>{load();},[]);
const openCreate=()=>{setEditing(null);setForm({ClientName:'',ClientTitle:'',ClientCompany:'',Review:'',Rating:5,IsActive:true});setErr('');setOpen(true);};
const openEdit=(r)=>{setEditing(r);setForm({ClientName:r.ClientName,ClientTitle:r.ClientTitle||'',ClientCompany:r.ClientCompany||'',Review:r.Review||'',Rating:r.Rating||5,IsActive:r.IsActive!==false});setErr('');setOpen(true);};
const save=async()=>{setSaving(true);setErr('');try{if(editing){await api.put(`/testimonials/${editing.TestimonialID}`,form);}else{await api.post('/testimonials',form);}setOpen(false);load();}catch(e){setErr(e.response?.data?.message||'Save failed');}finally{setSaving(false);}};
const del=async(id)=>{if(!window.confirm('Delete?'))return;await api.delete(`/testimonials/${id}`);load();};
return(<div className="p-6"><div className="flex items-center justify-between mb-6"><h1 className="text-2xl font-bold font-heading text-dark-800">Testimonials</h1><Button variant="contained" startIcon={<Add/>} onClick={openCreate} sx={{background:'linear-gradient(135deg,#0052cc,#003d99)'}}>Add Testimonial</Button></div>
{loading?<CircularProgress/>:<Table size="small"><TableHead><TableRow><TableCell>Client</TableCell><TableCell>Company</TableCell><TableCell>Rating</TableCell><TableCell>Active</TableCell><TableCell align="right">Actions</TableCell></TableRow></TableHead><TableBody>{rows.map(r=><TableRow key={r.TestimonialID} hover><TableCell><div className="font-medium">{r.ClientName}</div><div className="text-xs text-gray-400">{r.ClientTitle}</div></TableCell><TableCell>{r.ClientCompany||'-'}</TableCell><TableCell><Rating value={r.Rating} size="small" readOnly/></TableCell><TableCell><Chip label={r.IsActive?'Active':'Hidden'} color={r.IsActive?'success':'default'} size="small"/></TableCell><TableCell align="right"><IconButton size="small" onClick={()=>openEdit(r)}><Edit fontSize="small"/></IconButton><IconButton size="small" color="error" onClick={()=>del(r.TestimonialID)}><Delete fontSize="small"/></IconButton></TableCell></TableRow>)}</TableBody></Table>}
<Dialog open={open} onClose={()=>setOpen(false)} maxWidth="sm" fullWidth><DialogTitle>{editing?'Edit Testimonial':'Add Testimonial'}</DialogTitle><DialogContent><div className="space-y-4 pt-2">{err&&<Alert severity="error">{err}</Alert>}<TextField fullWidth label="Client Name *" required value={form.ClientName} onChange={e=>setForm(f=>({...f,ClientName:e.target.value}))}/><TextField fullWidth label="Job Title" value={form.ClientTitle} onChange={e=>setForm(f=>({...f,ClientTitle:e.target.value}))}/><TextField fullWidth label="Company" value={form.ClientCompany} onChange={e=>setForm(f=>({...f,ClientCompany:e.target.value}))}/><TextField fullWidth multiline rows={4} label="Review *" required value={form.Review} onChange={e=>setForm(f=>({...f,Review:e.target.value}))}/><div><div className="text-sm text-gray-600 mb-1">Rating</div><Rating value={Number(form.Rating)} onChange={(_,v)=>setForm(f=>({...f,Rating:v}))}/></div><div className="flex items-center gap-2"><Switch checked={form.IsActive} onChange={e=>setForm(f=>({...f,IsActive:e.target.checked}))}/><span className="text-sm text-gray-600">Show on website</span></div></div></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="contained" onClick={save} disabled={saving}>{saving?'Saving...':'Save'}</Button></DialogActions></Dialog></div>);}
