import React from'react';import{Helmet}from'react-helmet-async';import{motion}from'framer-motion';import{Link}from'react-router-dom';
const TEAM=[{name:'Ahmed Al-Rashidi',role:'CEO & Founder',bio:'20+ years in enterprise IT across the GCC region.'},{name:'Fatima Hassan',role:'CTO',bio:'Cloud and cybersecurity architect with AWS & Azure expertise.'},{name:'Khalid Nasser',role:'Head of CCTV & Surveillance',bio:'Certified in Hikvision, Axis, and AI-based video analytics.'},{name:'Sara Mohammed',role:'Head of Networking',role2:'CCNP, CCIE',bio:'Cisco gold-certified network design specialist.'}];
const VALUES=[{icon:'🛡️',title:'Security First',desc:'Every solution we deliver is built with security baked in from day one.'},{icon:'🚀',title:'Innovation',desc:'We continuously invest in the latest enterprise technologies.'},{icon:'🤝',title:'Partnership',desc:'We are not just a vendor — we are your long-term technology partner.'},{icon:'⭐',title:'Excellence',desc:'We hold ourselves to the highest standards of quality and delivery.'}];
const STATS=[{n:'500+',l:'Projects Delivered'},{n:'15+',l:'Years Experience'},{n:'200+',l:'Enterprise Clients'},{n:'50+',l:'Certified Engineers'}];
export default function About(){
return(<><Helmet><title>About Us – V-Trinity Solutions</title></Helmet>
<div style={{background:'linear-gradient(135deg,#0a0e1a,#0d1b3e)',paddingTop:80}}><div className="container-xl py-20"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="max-w-3xl"><span className="text-secondary-500 font-semibold text-sm uppercase tracking-widest">Who We Are</span><h1 className="text-5xl font-bold font-heading text-white mt-3 mb-6">About V-Trinity Solutions</h1><p className="text-gray-300 text-lg leading-relaxed">V-Trinity Solutions is a leading enterprise IT, CCTV surveillance, networking, cloud, and cybersecurity company serving governments, enterprises, and SMEs across the GCC region. Founded in 2009, we have delivered 500+ transformative technology projects.</p></motion.div></div></div>

<div className="section-padding bg-white"><div className="container-xl"><div className="grid lg:grid-cols-2 gap-16 items-center"><div><h2 className="text-3xl font-bold font-heading text-dark-800 mb-4">Our Mission</h2><p className="text-gray-600 leading-relaxed mb-4">To empower organizations with cutting-edge, secure, and scalable technology solutions that drive digital transformation, enhance operational efficiency, and protect critical assets.</p><p className="text-gray-600 leading-relaxed">We combine deep technical expertise with a consultative approach to ensure every solution aligns perfectly with your business objectives.</p><Link to="/contact" className="btn-primary mt-6 inline-block">Get in Touch</Link></div><div className="grid grid-cols-2 gap-4">{STATS.map(s=><motion.div key={s.l} initial={{opacity:0,scale:0.9}} whileInView={{opacity:1,scale:1}} viewport={{once:true}} className="bg-gradient-to-br from-primary-50 to-secondary-50 rounded-2xl p-6 text-center"><div className="text-4xl font-black text-primary-600">{s.n}</div><div className="text-gray-600 text-sm mt-1">{s.l}</div></motion.div>)}</div></div></div></div>

<div className="section-padding bg-gray-50"><div className="container-xl"><div className="text-center mb-12"><h2 className="text-3xl font-bold font-heading text-dark-800">Our Core Values</h2></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">{VALUES.map((v,i)=><motion.div key={v.title} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*0.1}} className="bg-white rounded-2xl p-6 text-center shadow-sm hover:shadow-md transition-shadow"><div className="text-4xl mb-3">{v.icon}</div><h3 className="font-bold text-dark-800 mb-2">{v.title}</h3><p className="text-gray-500 text-sm">{v.desc}</p></motion.div>)}</div></div></div>

<div className="section-padding bg-white"><div className="container-xl"><div className="text-center mb-12"><h2 className="text-3xl font-bold font-heading text-dark-800">Leadership Team</h2><p className="text-gray-500 mt-2">Meet the experts driving our mission forward</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">{TEAM.map((m,i)=><motion.div key={m.name} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*0.1}} className="text-center p-6 rounded-2xl border border-gray-100 hover:shadow-lg transition-shadow"><div className="w-20 h-20 rounded-full bg-gradient-to-br from-primary-400 to-secondary-400 flex items-center justify-center text-white text-2xl font-bold mx-auto mb-4">{m.name.charAt(0)}</div><h3 className="font-bold text-dark-800">{m.name}</h3><div className="text-primary-500 text-sm font-medium">{m.role}</div><p className="text-gray-500 text-sm mt-2">{m.bio}</p></motion.div>)}</div></div></div>

<div className="section-padding" style={{background:'linear-gradient(135deg,#0052cc,#00b4d8)'}}><div className="container-xl text-center"><h2 className="text-3xl font-bold font-heading text-white mb-4">Ready to Transform Your Business?</h2><p className="text-blue-100 mb-8 text-lg">Let's discuss how V-Trinity Solutions can help you achieve your technology goals.</p><div className="flex flex-wrap justify-center gap-4"><Link to="/request-solution" className="bg-white text-primary-600 font-semibold px-8 py-3 rounded-lg hover:shadow-lg transition-all">Request a Solution</Link><Link to="/contact" className="btn-outline">Contact Us</Link></div></div></div>
</>);}


