import React,{useEffect,useState}from'react';import{useParams,Link}from'react-router-dom';import{Helmet}from'react-helmet-async';import{CircularProgress,Chip,TextField,Button,Alert,Grid}from'@mui/material';import{motion}from'framer-motion';import api from'../../services/api';
export default function JobDetail(){const{slug}=useParams();const[job,setJob]=useState(null);const[loading,setLoading]=useState(true);const[applying,setApplying]=useState(false);const[form,setForm]=useState({fullName:'',email:'',phone:'',coverLetter:''});const[file,setFile]=useState(null);const[success,setSuccess]=useState(false);const[error,setError]=useState('');
useEffect(()=>{api.get(`/careers/${slug}`).then(r=>setJob(r.data.data)).catch(()=>{}).finally(()=>setLoading(false));},[slug]);
const handleApply=async(e)=>{e.preventDefault();setApplying(true);setError('');try{const fd=new FormData();Object.entries(form).forEach(([k,v])=>v&&fd.append(k,v));if(file)fd.append('resume',file);await api.post(`/careers/${job.JobID}/apply`,fd,{headers:{'Content-Type':'multipart/form-data'}});setSuccess(true);}catch(err){setError(err.response?.data?.message||'Application failed. Please try again.');}finally{setApplying(false);}};
if(loading)return<div className="flex justify-center items-center min-h-screen"><CircularProgress/></div>;
if(!job)return<div className="text-center py-32"><h2 className="text-2xl text-gray-500">Job not found</h2><Link to="/careers" className="text-primary-500 mt-4 inline-block">← Back to Careers</Link></div>;
return(<><Helmet><title>{job.Title} – V-Trinity Solutions Careers</title></Helmet>
<div style={{background:'linear-gradient(135deg,#0a0e1a,#0d1b3e)',paddingTop:80}}><div className="container-xl py-16"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}>
<Link to="/careers" className="text-gray-400 hover:text-white text-sm mb-4 inline-block">← Back to Careers</Link>
<h1 className="text-4xl font-bold font-heading text-white mb-3">{job.Title}</h1>
<div className="flex flex-wrap items-center gap-3">{job.DepartmentName&&<Chip label={job.DepartmentName} sx={{color:'#fff',bgcolor:'rgba(255,255,255,0.15)'}}/>}{job.Location&&<Chip label={job.Location} sx={{color:'#fff',bgcolor:'rgba(255,255,255,0.1)'}}/>}{job.JobType&&<Chip label={job.JobType} color="secondary"/>}</div>
</motion.div></div></div>
<div className="section-padding bg-white"><div className="container-xl"><div className="grid lg:grid-cols-3 gap-10">
<div className="lg:col-span-2 space-y-6">
{job.Description&&<div><h2 className="text-xl font-bold text-dark-800 mb-3">About the Role</h2><div className="text-gray-600 leading-relaxed whitespace-pre-wrap">{job.Description}</div></div>}
{job.Requirements&&<div><h2 className="text-xl font-bold text-dark-800 mb-3">Requirements</h2><div className="text-gray-600 leading-relaxed whitespace-pre-wrap">{job.Requirements}</div></div>}
{job.Benefits&&<div><h2 className="text-xl font-bold text-dark-800 mb-3">Benefits</h2><div className="text-gray-600 leading-relaxed whitespace-pre-wrap">{job.Benefits}</div></div>}
<div className="mt-8 p-6 bg-gray-50 rounded-2xl">{success?<Alert severity="success" sx={{mb:2}}>Application submitted! We will review and contact you soon.</Alert>:<><h2 className="text-xl font-bold text-dark-800 mb-5">Apply for this Position</h2>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<form onSubmit={handleApply}><Grid container spacing={2}><Grid item xs={12} sm={6}><TextField fullWidth label="Full Name *" required value={form.fullName} onChange={e=>setForm(f=>({...f,fullName:e.target.value}))}/></Grid><Grid item xs={12} sm={6}><TextField fullWidth label="Email *" type="email" required value={form.email} onChange={e=>setForm(f=>({...f,email:e.target.value}))}/></Grid><Grid item xs={12} sm={6}><TextField fullWidth label="Phone *" required value={form.phone} onChange={e=>setForm(f=>({...f,phone:e.target.value}))}/></Grid><Grid item xs={12} sm={6}><TextField fullWidth label="LinkedIn URL" value={form.linkedInURL||''} onChange={e=>setForm(f=>({...f,linkedInURL:e.target.value}))}/></Grid><Grid item xs={12}><TextField fullWidth multiline rows={4} label="Cover Letter" value={form.coverLetter} onChange={e=>setForm(f=>({...f,coverLetter:e.target.value}))}/></Grid><Grid item xs={12}><div className="border-2 border-dashed border-gray-200 rounded-lg p-4 cursor-pointer text-center" onClick={()=>document.getElementById('resume').click()}><input id="resume" type="file" hidden accept=".pdf,.doc,.docx" onChange={e=>setFile(e.target.files[0])}/>{file?<span className="text-primary-500 text-sm font-medium">📄 {file.name}</span>:<span className="text-gray-400 text-sm">📎 Upload Resume (PDF/Word)</span>}</div></Grid><Grid item xs={12}><Button type="submit" variant="contained" size="large" disabled={applying} sx={{py:1.5,background:'linear-gradient(135deg,#0052cc,#003d99)'}}>{applying?'Submitting...':'Submit Application →'}</Button></Grid></Grid></form></>}</div>
</div>
<div><div className="bg-gray-50 rounded-2xl p-6 sticky top-24 space-y-3"><h3 className="font-bold text-dark-800 mb-2">Job Details</h3>{[['Dept',job.DepartmentName],['Type',job.JobType],['Location',job.Location],['Experience',job.ExperienceMin&&`${job.ExperienceMin}${job.ExperienceMax?`-${job.ExperienceMax}`:'+'}  years`],['Salary',job.Salary],['Deadline',job.ExpiresAt&&new Date(job.ExpiresAt).toLocaleDateString()]].filter(([,v])=>v).map(([k,v])=><div key={k}><span className="text-xs text-gray-400 uppercase font-semibold">{k}</span><div className="font-medium text-dark-800 text-sm">{v}</div></div>)}</div></div>
</div></div></div></>);}


