import React,{useEffect,useState}from'react';import{Link,useSearchParams}from'react-router-dom';import{Helmet}from'react-helmet-async';import{CircularProgress,Chip}from'@mui/material';import{motion}from'framer-motion';import api from'../../services/api';
export default function Projects(){const[projects,setProjects]=useState([]);const[industries,setIndustries]=useState([]);const[loading,setLoading]=useState(true);const[total,setTotal]=useState(0);const[page,setPage]=useState(1);const[searchParams,setSearchParams]=useSearchParams();const industry=searchParams.get('ind')||'';
useEffect(()=>{setLoading(true);const params=new URLSearchParams({page,limit:12,...(industry&&{industry})});Promise.all([api.get(`/projects?${params}`),api.get('/public/industries')]).then(([p,i])=>{setProjects(p.data.data);setTotal(p.data.pagination?.total||0);setIndustries(i.data.data);}).catch(()=>{}).finally(()=>setLoading(false));},[page,industry]);
return(<><Helmet><title>Projects – V-Trinity Solutions</title></Helmet>
<div style={{background:'linear-gradient(135deg,#0a0e1a,#0d1b3e)',paddingTop:80}}><div className="container-xl py-16 text-center"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}><span className="text-secondary-500 font-semibold text-sm uppercase tracking-widest">Our Portfolio</span><h1 className="text-5xl font-bold font-heading text-white mt-3 mb-4">Project Portfolio</h1><p className="text-gray-300 text-lg max-w-xl mx-auto">500+ successful projects across government, enterprise and industrial sectors.</p></motion.div></div></div>
<div className="section-padding bg-white"><div className="container-xl">
<div className="flex flex-wrap gap-2 mb-8"><Chip label="All Industries" clickable variant={!industry?'filled':'outlined'} color={!industry?'primary':'default'} onClick={()=>{setSearchParams({});setPage(1);}}/>{industries.map(i=><Chip key={i.Slug} label={i.Name} clickable variant={industry===i.Slug?'filled':'outlined'} color={industry===i.Slug?'primary':'default'} onClick={()=>{setSearchParams({ind:i.Slug});setPage(1);}}/>)}</div>
{loading?<div className="text-center py-16"><CircularProgress/></div>:<>
<div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">{projects.map((p,i)=><motion.div key={p.ProjectID} initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:i*0.04}}>
<Link to={`/projects/${p.Slug}`} className="block rounded-2xl overflow-hidden border border-gray-100 hover:shadow-xl transition-all group">
<div className="h-52 bg-gradient-to-br from-primary-600 to-secondary-500 overflow-hidden relative">{p.ThumbnailURL?<img src={p.ThumbnailURL} alt={p.ProjectName} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"/>:<div className="w-full h-full flex items-center justify-center text-6xl opacity-40">🏗️</div>}{p.IsFeatured&&<span className="absolute top-3 right-3 bg-accent-500 text-white text-xs px-2 py-1 rounded-full font-semibold">Featured</span>}</div>
<div className="p-5"><span className="text-xs font-semibold text-primary-500 uppercase">{p.IndustryName}</span><h3 className="font-bold text-dark-800 mt-1 mb-1">{p.ProjectName}</h3><p className="text-gray-500 text-sm">{p.ClientName}{p.Location&&` · ${p.Location}`}</p></div></Link></motion.div>)}
</div>
{total>12&&<div className="flex justify-center gap-2 mt-10"><button onClick={()=>setPage(p=>p-1)} disabled={page===1} className="px-4 py-2 rounded-lg border border-gray-200 text-sm disabled:opacity-40">← Prev</button><span className="px-4 py-2 text-sm text-gray-500">Page {page} of {Math.ceil(total/12)}</span><button onClick={()=>setPage(p=>p+1)} disabled={page*12>=total} className="px-4 py-2 rounded-lg border border-gray-200 text-sm disabled:opacity-40">Next →</button></div>}
</>}</div></div></>);}


